.PHONY: clean All

All:
	@echo "----------Building project:[ Garden - Debug ]----------"
	@cd "Garden" && "$(MAKE)" -f  "Garden.mk"
clean:
	@echo "----------Cleaning project:[ Garden - Debug ]----------"
	@cd "Garden" && "$(MAKE)" -f  "Garden.mk" clean
